// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_dash.Infrastructure.Data;

#nullable disable

namespace backend_dash.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250828131914_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend_dash.Domain.DigitalFactory", b =>
                {
                    b.Property<string>("Ref")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Ref");

                    b.ToTable("DigitalFactories", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.DigitalModule", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("ComponentState")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FactoryId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("FINISHED");

                    b.Property<string>("TopicCommand")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TopicState")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("SerialNumber");

                    b.HasIndex("FactoryId");

                    b.ToTable("DigitalModules", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("backend_dash.Domain.TaskFixedModule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FixedModuleId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FixedModuleId");

                    b.ToTable("TaskFixedModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.FixedModule", b =>
                {
                    b.HasBaseType("backend_dash.Domain.DigitalModule");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable("FixedModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.Store", b =>
                {
                    b.HasBaseType("backend_dash.Domain.DigitalModule");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.TransportModule", b =>
                {
                    b.HasBaseType("backend_dash.Domain.DigitalModule");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.ToTable("TransportModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.StorageModule", b =>
                {
                    b.HasBaseType("backend_dash.Domain.FixedModule");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.HasIndex("StoreId");

                    b.ToTable("StorageModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.DigitalModule", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalFactory", "factory")
                        .WithMany("DigitalModules")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("factory");
                });

            modelBuilder.Entity("backend_dash.Domain.TaskFixedModule", b =>
                {
                    b.HasOne("backend_dash.Domain.FixedModule", null)
                        .WithMany("Proces")
                        .HasForeignKey("FixedModuleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend_dash.Domain.FixedModule", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.FixedModule", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_dash.Domain.Store", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.Store", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_dash.Domain.TransportModule", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.TransportModule", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_dash.Domain.StorageModule", b =>
                {
                    b.HasOne("backend_dash.Domain.FixedModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.StorageModule", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dash.Domain.Store", null)
                        .WithMany("StorageModules")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend_dash.Domain.DigitalFactory", b =>
                {
                    b.Navigation("DigitalModules");
                });

            modelBuilder.Entity("backend_dash.Domain.FixedModule", b =>
                {
                    b.Navigation("Proces");
                });

            modelBuilder.Entity("backend_dash.Domain.Store", b =>
                {
                    b.Navigation("StorageModules");
                });
#pragma warning restore 612, 618
        }
    }
}
