// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_dash.Infrastructure.Data;

#nullable disable

namespace backend_dash.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250905144957_updatedOrder")]
    partial class updatedOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkpieceTypeFixedModule", b =>
                {
                    b.Property<string>("WorkpieceTypeId")
                        .HasColumnType("text");

                    b.Property<string>("FixedModuleId")
                        .HasColumnType("text");

                    b.HasKey("WorkpieceTypeId", "FixedModuleId");

                    b.HasIndex("FixedModuleId");

                    b.ToTable("WorkpieceTypeFixedModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.Command", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<int>("OrderUpdateId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Commands", (string)null);

                    b.HasDiscriminator<string>("CommandType").HasValue("Command");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend_dash.Domain.DigitalFactory", b =>
                {
                    b.Property<string>("Ref")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Ref");

                    b.ToTable("DigitalFactories", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.DigitalModule", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("ComponentState")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FactoryId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("FINISHED");

                    b.Property<string>("TopicCommand")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TopicState")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("SerialNumber");

                    b.HasIndex("FactoryId");

                    b.ToTable("DigitalModules", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("backend_dash.Domain.ModuleLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ModuleSerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("wpId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ModuleLogs", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);

                    b.HasDiscriminator<string>("OrderType").HasValue("Order");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend_dash.Domain.TaskFixedModule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FixedModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FixedModuleId");

                    b.ToTable("TaskFixedModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.Workpiece", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TypeId");

                    b.ToTable("Workpieces", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.WorkpieceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ModuleSerial")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkpieceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WorkpieceType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("WorkpieceLogs", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.WorkpieceType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StoreSerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("TransportModuleSerialNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoreSerialNumber");

                    b.HasIndex("TransportModuleSerialNumber");

                    b.ToTable("WorkpieceTypes", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.StoreCommand", b =>
                {
                    b.HasBaseType("backend_dash.Domain.Command");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkpieceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("STORE");
                });

            modelBuilder.Entity("backend_dash.Domain.TaskCommand", b =>
                {
                    b.HasBaseType("backend_dash.Domain.Command");

                    b.HasDiscriminator().HasValue("TASK");
                });

            modelBuilder.Entity("backend_dash.Domain.TransportCommand", b =>
                {
                    b.HasBaseType("backend_dash.Domain.Command");

                    b.Property<string>("FromNodeRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToNodeRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("TRANSPORT");
                });

            modelBuilder.Entity("backend_dash.Domain.FixedModule", b =>
                {
                    b.HasBaseType("backend_dash.Domain.DigitalModule");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable("FixedModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.Store", b =>
                {
                    b.HasBaseType("backend_dash.Domain.DigitalModule");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.TransportModule", b =>
                {
                    b.HasBaseType("backend_dash.Domain.DigitalModule");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.ToTable("TransportModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.ProductionOrder", b =>
                {
                    b.HasBaseType("backend_dash.Domain.Order");

                    b.HasDiscriminator().HasValue("PRODUCTION");
                });

            modelBuilder.Entity("backend_dash.Domain.StoreWorkpiecesOrder", b =>
                {
                    b.HasBaseType("backend_dash.Domain.Order");

                    b.HasDiscriminator().HasValue("STORE");
                });

            modelBuilder.Entity("backend_dash.Domain.StorageModule", b =>
                {
                    b.HasBaseType("backend_dash.Domain.FixedModule");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.HasIndex("StoreId");

                    b.ToTable("StorageModules", (string)null);
                });

            modelBuilder.Entity("WorkpieceTypeFixedModule", b =>
                {
                    b.HasOne("backend_dash.Domain.FixedModule", null)
                        .WithMany()
                        .HasForeignKey("FixedModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dash.Domain.WorkpieceType", null)
                        .WithMany()
                        .HasForeignKey("WorkpieceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_dash.Domain.Command", b =>
                {
                    b.HasOne("backend_dash.Domain.Order", "Order")
                        .WithMany("Commands")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("backend_dash.Domain.DigitalModule", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalFactory", "factory")
                        .WithMany("DigitalModules")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("factory");
                });

            modelBuilder.Entity("backend_dash.Domain.TaskFixedModule", b =>
                {
                    b.HasOne("backend_dash.Domain.FixedModule", "FixedModule")
                        .WithMany("Proces")
                        .HasForeignKey("FixedModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FixedModule");
                });

            modelBuilder.Entity("backend_dash.Domain.Workpiece", b =>
                {
                    b.HasOne("backend_dash.Domain.Order", "Order")
                        .WithMany("Workpieces")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("backend_dash.Domain.WorkpieceType", "Type")
                        .WithMany("Workpieces")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("backend_dash.Domain.WorkpieceType", b =>
                {
                    b.HasOne("backend_dash.Domain.Store", null)
                        .WithMany("CompatibleWorkpieceTypes")
                        .HasForeignKey("StoreSerialNumber");

                    b.HasOne("backend_dash.Domain.TransportModule", null)
                        .WithMany("CompatibleWorkpieceTypes")
                        .HasForeignKey("TransportModuleSerialNumber");
                });

            modelBuilder.Entity("backend_dash.Domain.FixedModule", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.FixedModule", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_dash.Domain.Store", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.Store", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_dash.Domain.TransportModule", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.TransportModule", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_dash.Domain.StorageModule", b =>
                {
                    b.HasOne("backend_dash.Domain.FixedModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.StorageModule", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dash.Domain.Store", null)
                        .WithMany("StorageModules")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend_dash.Domain.DigitalFactory", b =>
                {
                    b.Navigation("DigitalModules");
                });

            modelBuilder.Entity("backend_dash.Domain.Order", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("Workpieces");
                });

            modelBuilder.Entity("backend_dash.Domain.WorkpieceType", b =>
                {
                    b.Navigation("Workpieces");
                });

            modelBuilder.Entity("backend_dash.Domain.FixedModule", b =>
                {
                    b.Navigation("Proces");
                });

            modelBuilder.Entity("backend_dash.Domain.Store", b =>
                {
                    b.Navigation("CompatibleWorkpieceTypes");

                    b.Navigation("StorageModules");
                });

            modelBuilder.Entity("backend_dash.Domain.TransportModule", b =>
                {
                    b.Navigation("CompatibleWorkpieceTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
