// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_dash.Infrastructure.Data;

#nullable disable

namespace backend_dash.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250928204625_fixTrywithnew")]
    partial class fixTrywithnew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StorageSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("StorageModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StorageModuleId");

                    b.ToTable("StorageSlots", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.AlertEntity", b =>
                {
                    b.Property<string>("AlertId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AlertType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DigitalModuleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SensorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Summary")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("AlertId");

                    b.ToTable("AlertsLog", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.DigitalFactory", b =>
                {
                    b.Property<string>("Ref")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Ref");

                    b.ToTable("DigitalFactories", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.DigitalModule", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("ComponentState")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FactoryId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("FINISHED");

                    b.Property<string>("TopicCommand")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TopicState")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("SerialNumber");

                    b.HasIndex("FactoryId");

                    b.ToTable("DigitalModules", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("backend_dash.Domain.ModuleLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ModuleSerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModuleState")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("wpId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ModuleLogs", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);

                    b.HasDiscriminator<string>("OrderType").HasValue("Order");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend_dash.Domain.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.Sensor", b =>
                {
                    b.Property<string>("SensorId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DigitalModuleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SensorId");

                    b.HasIndex("DigitalModuleId");

                    b.ToTable("Sensors", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.SensorLog", b =>
                {
                    b.Property<string>("SensorId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ValueNumeric")
                        .HasColumnType("double precision");

                    b.Property<string>("ValueRaw")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("SensorId", "Timestamp");

                    b.ToTable("SensorLogs", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.TaskFixedModule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FixedModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FixedModuleId");

                    b.ToTable("TaskFixedModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.UserAccess", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("FactoryId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasAccess")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "FactoryId");

                    b.HasIndex("FactoryId");

                    b.ToTable("UserAccesses", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.Workpiece", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("FREE");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Workpieces", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.WorkpieceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ModuleSerial")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkpieceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WorkpieceType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("WorkpieceId");

                    b.ToTable("WorkpieceLogs", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.WorkpieceType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("WorkpieceTypes", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.WorkpieceTypeModule", b =>
                {
                    b.Property<string>("WorkpieceTypeId")
                        .HasColumnType("text");

                    b.Property<string>("FixedModuleId")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("WorkpieceTypeId", "FixedModuleId");

                    b.HasIndex("FixedModuleId");

                    b.ToTable("WorkpieceTypeModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.FixedModule", b =>
                {
                    b.HasBaseType("backend_dash.Domain.DigitalModule");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable("FixedModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.Store", b =>
                {
                    b.HasBaseType("backend_dash.Domain.DigitalModule");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.TransportModule", b =>
                {
                    b.HasBaseType("backend_dash.Domain.DigitalModule");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.ToTable("TransportModules", (string)null);
                });

            modelBuilder.Entity("backend_dash.Domain.ProductionOrder", b =>
                {
                    b.HasBaseType("backend_dash.Domain.Order");

                    b.HasDiscriminator().HasValue("PRODUCTION");
                });

            modelBuilder.Entity("backend_dash.Domain.RetrieveWorkpiecesOrder", b =>
                {
                    b.HasBaseType("backend_dash.Domain.Order");

                    b.HasDiscriminator().HasValue("RETRIEVE FROM STORE");
                });

            modelBuilder.Entity("backend_dash.Domain.StoreWorkpiecesOrder", b =>
                {
                    b.HasBaseType("backend_dash.Domain.Order");

                    b.HasDiscriminator().HasValue("ADD TO STORE");
                });

            modelBuilder.Entity("backend_dash.Domain.StorageModule", b =>
                {
                    b.HasBaseType("backend_dash.Domain.FixedModule");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.HasIndex("StoreId");

                    b.ToTable("StorageModules", (string)null);
                });

            modelBuilder.Entity("StorageSlot", b =>
                {
                    b.HasOne("backend_dash.Domain.StorageModule", "StorageModule")
                        .WithMany("Slots")
                        .HasForeignKey("StorageModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageModule");
                });

            modelBuilder.Entity("backend_dash.Domain.DigitalModule", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalFactory", "factory")
                        .WithMany("DigitalModules")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("factory");
                });

            modelBuilder.Entity("backend_dash.Domain.RefreshToken", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_dash.Domain.Sensor", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalModule", "DigitalModule")
                        .WithMany()
                        .HasForeignKey("DigitalModuleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DigitalModule");
                });

            modelBuilder.Entity("backend_dash.Domain.SensorLog", b =>
                {
                    b.HasOne("backend_dash.Domain.Sensor", null)
                        .WithMany("Logs")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_dash.Domain.TaskFixedModule", b =>
                {
                    b.HasOne("backend_dash.Domain.FixedModule", "FixedModule")
                        .WithMany("Proces")
                        .HasForeignKey("FixedModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FixedModule");
                });

            modelBuilder.Entity("backend_dash.Domain.UserAccess", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalFactory", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend_dash.Domain.Workpiece", b =>
                {
                    b.HasOne("backend_dash.Domain.WorkpieceType", "Type")
                        .WithMany("Workpieces")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("backend_dash.Domain.WorkpieceLog", b =>
                {
                    b.HasOne("backend_dash.Domain.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_WorkpieceLogs_Order");

                    b.HasOne("backend_dash.Domain.Workpiece", null)
                        .WithMany()
                        .HasForeignKey("WorkpieceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WorkpieceLogs_Workpiece");
                });

            modelBuilder.Entity("backend_dash.Domain.WorkpieceTypeModule", b =>
                {
                    b.HasOne("backend_dash.Domain.FixedModule", "FixedModule")
                        .WithMany("CompatibleWorkpieceTypesLinks")
                        .HasForeignKey("FixedModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dash.Domain.WorkpieceType", "WorkpieceType")
                        .WithMany("ModuleLinks")
                        .HasForeignKey("WorkpieceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FixedModule");

                    b.Navigation("WorkpieceType");
                });

            modelBuilder.Entity("backend_dash.Domain.FixedModule", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.FixedModule", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_dash.Domain.Store", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.Store", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_dash.Domain.TransportModule", b =>
                {
                    b.HasOne("backend_dash.Domain.DigitalModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.TransportModule", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend_dash.Domain.StorageModule", b =>
                {
                    b.HasOne("backend_dash.Domain.FixedModule", null)
                        .WithOne()
                        .HasForeignKey("backend_dash.Domain.StorageModule", "SerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend_dash.Domain.Store", null)
                        .WithMany("StorageModules")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("backend_dash.Domain.DigitalFactory", b =>
                {
                    b.Navigation("DigitalModules");
                });

            modelBuilder.Entity("backend_dash.Domain.Sensor", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("backend_dash.Domain.WorkpieceType", b =>
                {
                    b.Navigation("ModuleLinks");

                    b.Navigation("Workpieces");
                });

            modelBuilder.Entity("backend_dash.Domain.FixedModule", b =>
                {
                    b.Navigation("CompatibleWorkpieceTypesLinks");

                    b.Navigation("Proces");
                });

            modelBuilder.Entity("backend_dash.Domain.Store", b =>
                {
                    b.Navigation("StorageModules");
                });

            modelBuilder.Entity("backend_dash.Domain.StorageModule", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
